[package]
name = "quicksilver"
description = "A simple game framework for 2D games in pure Rust"
version = "0.3.22"
authors = ["Ryan Goldstein <ryanisaacg@gmail.com>"]
categories = ["game-engines"]
homepage = "https://ryanisaacg.github.io/quicksilver"
keywords = ["game", "audio", "graphics", "gamedev"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/ryanisaacg/quicksilver"
exclude = ["docs/*"]
edition = "2018"

[features]
default = ["collisions", "complex_shapes", "immi_ui", "fonts", "gamepads", "saving", "sounds"]

collisions = ["nalgebra", "ncollide2d"]
complex_shapes = ["lyon"]
fonts = ["rusttype"]
gamepads = ["gilrs"]
immi_ui = ["immi", "fonts"]
saving = ["dirs", "serde_json"]
sounds = ["rodio"]

[badges]

travis-ci = { repository = "ryanisaacg/quicksilver", branch = "master" }
maintenance = { status = "actively-developed" }

[dependencies]
futures = "0.1"
gilrs = { version = "0.7", optional = true }
lyon = { version = "0.14", features = ["extra"], optional = true }
rand = { version = "0.7" }
serde = "1.0"
serde_derive = "1.0"
nalgebra = { version = "0.20", optional = true }
ncollide2d = { version = "0.22", optional = true }
immi = { version = "1.0", optional = true }
rusttype = { version = "0.7", optional = true }
serde_json = { version = "1.0", optional = true }

[dev-dependencies]
alga = "0.9"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
dirs = { version = "2.0", optional = true }
gl = "0.13"
glutin = { version = "0.21" }
image = "0.21"
winit = { version = "0.19.1", features = ["icon_loading"] }
rodio = { version = "0.11", optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
image = { version = "0.22", default-features = false, features = ["png_codec", "jpeg"] }
stdweb = "0.4.16"
base64 = "0.10"
# webgl_stdweb = "0.3"
webgl_stdweb = { git = "https://github.com/SafariMonkey/gl-rs", branch = "wasm-bindgen-support" }

[target.'cfg(all(target_arch = "wasm32", not(cargo_web)))'.dependencies]
wasm-bindgen = "0.2.60"

[[example]]
name = "draw-geometry"
required-features = []

[[example]]
name = "image"
required-features = []

[[example]]
name = "font"
required-features = ["fonts"]

[[example]]
name = "sound"
required-features = ["sounds"]

[[example]]
name = "raycast"
required-features = ["collisions"]

[[example]]
name = "rgb-triangle"
required-features = []

[[example]]
name = "lyon"
required-features = ["complex_shapes"]

[[example]]
name = "set-cursor"
required-features = []

[[example]]
name = "stopwatch"
required-features = []

[[example]]
name = "camera"
required-features = []

